export const moviesForWatched = [
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
        id: 603,
        original_title: "The Matrix",
        overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
        popularity: 55.714,
        poster_path: "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        release_date: "1999-03-30",
        title: "The Matrix",
        vote_average: 8.2,
        vote_count: 19600,
        genres: "Action, Science Fiction",
        year: "1999",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/sDxCd4nt3eR4qOCW1GoD0RabQtq.jpg",
        id: 604,
        original_title: "The Matrix Reloaded",
        overview: "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
        popularity: 40.25,
        poster_path: "https://image.tmdb.org/t/p/original/8xEVAe84zlL9rkfYT6dZXero4KK.jpg",
        release_date: "2003-05-15",
        title: "The Matrix Reloaded",
        vote_average: 7,
        vote_count: 8009,
        genres: "Adventure, Action, Thriller, Science Fiction",
        year: "2003",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/t9dumNakkt6yL9wreEp35T4Lwny.jpg",
        id: 605,
        original_title: "The Matrix Revolutions",
        overview: "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
        popularity: 33.277,
        poster_path: "https://image.tmdb.org/t/p/original/fgm8OZ7o4G1G1I9EeGcb85Noe6L.jpg",
        release_date: "2003-11-03",
        title: "The Matrix Revolutions",
        vote_average: 6.7,
        vote_count: 7171,
        genres: "Adventure, Action, Thriller, Science Fiction",
        year: "2003",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/originalnull",
        id: 624860,
        original_title: "The Matrix Resurrections",
        overview: "The fourth installment in The Matrix franchise. Plot unknown.",
        popularity: 22.008,
        poster_path: "https://image.tmdb.org/t/p/original/aLs8CRWr6mXTi7fTUzm5p66NXo7.jpg",
        release_date: "2021-12-15",
        title: "The Matrix Resurrections",
        vote_average: 0,
        vote_count: 0,
        genres: "Action, Science Fiction, Adventure",
        year: "2021",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/lBdXACywnLwKUZmZkZ87djDQBeV.jpg",
        id: 14543,
        original_title: "The Matrix Revisited",
        overview: "The film goes behind the scenes of the 1999 sci-fi movie The Matrix.",
        popularity: 9.426,
        poster_path: "https://image.tmdb.org/t/p/original/fNG2JOskhQnttmAaj2knM5h59Io.jpg",
        release_date: "2001-11-19",
        title: "The Matrix Revisited",
        vote_average: 6.9,
        vote_count: 142,
        genres: "Documentary",
        year: "2001",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/originalnull",
        id: 51767,
        original_title: "Sexual Matrix",
        overview: "A professor designing a machine designed to meet the naughtiest fantasies. In order to perfect the discovery, he performed tests on various subjects, aided by his very appealing assistant.",
        popularity: 5.562,
        poster_path: "https://image.tmdb.org/t/p/original/vmhBIPKyYCWlp2PrIIc6EXZlP9Z.jpg",
        release_date: "2000-04-01",
        title: "Sexual Matrix",
        vote_average: 6.2,
        vote_count: 9,
        genres: "Science Fiction",
        year: "2000",
    },
];
export const moviesForQueue = [
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/nAhKxK8inVjHeHAw6W2xkQjdbh5.jpg",
        id: 119698,
        original_title: "The Dinosaur Project",
        overview: "Found footage of an expedition into the Congo jungle where a team of explorers stumbles upon a colony of Dinosaurs.",
        popularity: 27.853,
        poster_path: "https://image.tmdb.org/t/p/original/rUAsgohDDBWLb24FyxdjEZQPava.jpg",
        release_date: "2012-08-09",
        title: "The Dinosaur Project",
        vote_average: 4.7,
        vote_count: 131,
        genres: "Adventure, Action",
        year: "2012",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/dEIsdH9vVj6aIvP9uLMZmA3NJxH.jpg",
        id: 433763,
        original_title: "Amelie rennt",
        overview: "A girl struggling with asthma is taken to a clinic in South Tyrol to be cured. After some time she decides to get out of this hell (that's how she feels about it) and soon she'll meet a new friend. Together they try to reach the peak of a mountain where, according to an old custom, she can be healed.",
        popularity: 3.699,
        poster_path: "https://image.tmdb.org/t/p/original/6x9V3gr6k1FMi21uPDlVfiVtdvS.jpg",
        release_date: "2017-09-21",
        title: "Mountain Miracle",
        vote_average: 6.3,
        vote_count: 39,
        genres: "Family, Adventure",
        year: "2017",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/rFzedAcbusHXdAJxJf6t523mqFk.jpg",
        id: 854,
        original_title: "The Mask",
        overview: "When timid bank clerk Stanley Ipkiss discovers a magical mask containing the spirit of the Norse god Loki, his entire life changes. While wearing the mask, Ipkiss becomes a supernatural playboy exuding charm and confidence which allows him to catch the eye of local nightclub singer Tina Carlyle. Unfortunately, under the mask's influence, Ipkiss also robs a bank, which angers junior crime lord Dorian Tyrell, whose goons get blamed for the heist.",
        popularity: 48.423,
        poster_path: "https://image.tmdb.org/t/p/original/zJUvFtaGPQkcQYE8nmhU66ESpWe.jpg",
        release_date: "1994-07-29",
        title: "The Mask",
        vote_average: 6.9,
        vote_count: 7756,
        genres: "Romance, Comedy, Crime, Fantasy",
        year: "1994",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/bMZyC1XXHgcrrjpCQWKfUxhQ8PR.jpg",
        id: 9285,
        original_title: "Road Trip",
        overview: "From the director of the Hangover trilogy and Joker, Road Trip is a raunchy college comedy classic.  After an Ithaca college student films his one-night stand with a beautiful sorority girl, he discovers one of his friends has accidentally mailed the homemade porn tape to his girlfriend. In a frenzy, he must borrow a car and hit the road in a desperate bid to intercept the tape.  Featuring a talented cast that includes Breckin Meyer, Rachel Blanchard, Seann William Scott, Amy Smart, Fred Ward, Tom Green, Anthony Rapp, Andy Dick, and Ethan Suplee.",
        popularity: 15.116,
        poster_path: "https://image.tmdb.org/t/p/original/jee4eY5tZprI0V18S6PXUloBzSk.jpg",
        release_date: "2000-05-19",
        title: "Road Trip",
        vote_average: 6.1,
        vote_count: 1383,
        genres: "Comedy, Adventure",
        year: "2000",
    },
    {
        backdrop_path: "https://image.tmdb.org/t/p/original/eWZhoFrE5UtqSxApCO76ChoGQpW.jpg",
        id: 10999,
        original_title: "Commando",
        overview: "John Matrix, the former leader of a special commando strike force that always got the toughest jobs done, is forced back into action when his young daughter is kidnapped. To find her, Matrix has to fight his way through an array of punks, killers, one of his former commandos, and a fully equipped private army. With the help of a feisty stewardess and an old friend, Matrix has only a few hours to overcome his greatest challenge: finding his daughter before she's killed.",
        popularity: 21.973,
        poster_path: "https://image.tmdb.org/t/p/original/ollPAAAgZ7euU8VisfqU3cuXhZ6.jpg",
        release_date: "1985-10-03",
        title: "Commando",
        vote_average: 6.6,
        vote_count: 1940,
        genres: "Action, Adventure, Thriller",
        year: "1985",
    },
]